# -*- coding: utf-8 -*-
"""cleaning_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7FQpJk8iYIr0eVU_0Xc9XYEfvky6yuG

### **Required libraries**
"""

import pandas as pd
import kagglehub
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

"""

### **Task1** - load the dataset"""

def load_data():
    # download dataset from Kaggle
    path = kagglehub.dataset_download("prevek18/ames-housing-dataset")

    # build CSV path
    csv_path = os.path.join(path, "AmesHousing.csv")
    df = pd.read_csv(csv_path)
    return df

df = load_data()
df.head() #shows first 5 rows

"""### **Task2** - Checking the shape"""

def check_shape(df):
  return df.shape  # returns number of (rows, columns)
check_shape(df)

"""### **Task3** - Inspect data types"""

df.info() # Inspect current data types

def fix_data_types(df):
    df = df.copy()

    df["Neighborhood"] = df["Neighborhood"].astype(str).str.lower().str.strip()
    df["Sale Type"] = df["Sale Type"].astype(str).str.lower().str.strip()

    df["Central Air"] = df["Central Air"].astype(str).str.strip().map({"Y": 1, "N": 0})  # convert binary column to integer
    return df


fix_data_types(df)

"""### **Task4** - Find missing values"""

df.isnull().sum().sort_values(ascending=False) # check number of missing values per column

def handle_missing_values(df):
    df = df.copy()

    df = df.drop(columns=["Pool QC", "Misc Feature", "Alley"], errors="ignore") # drop columns with extremely missing values

    # specific logical fills
    df["Mas Vnr Type"] = df["Mas Vnr Type"].fillna("None") # filled with "None" because missing likely means feature does not exist
    df["Lot Frontage"] = df["Lot Frontage"].fillna(df["Lot Frontage"].median()) # filled with median to reduce effect of outliers
    df["Garage Yr Blt"] = df["Garage Yr Blt"].fillna(df["Garage Yr Blt"].median()) # filled with median to preserve numerical consistency

    df[df.select_dtypes(include=["int64", "float64"]).columns] = (
        df.select_dtypes(include=["int64", "float64"])
        .fillna(df.select_dtypes(include=["int64", "float64"]).median()))     # fill remaining numeric columns with median (robust against extreme values)

    df[df.select_dtypes(include=["object"]).columns] = (df.select_dtypes(include=["object"]).fillna("None")) # fill remaining object columns with "None" to indicate absence

    return df
handle_missing_values(df)

"""### **Task5** - Handle duplicates"""

df.duplicated().sum() # count duplicate rows

def remove_duplicates(df):
  df=df.copy()
  df.drop_duplicates() # drop duplicate rows
  return df
remove_duplicates(df)

"""### **Task6** -  Spot outliers"""

def cap_outliers(df):
    df = df.copy()

    plt.figure(figsize=(8,5))
    sns.boxplot(x=df["SalePrice"])
    plt.title("Boxplot of SalePrice before capping")
    plt.xlabel("SalePrice")
    plt.show() # Boxplot before capping

    upper_price = df["SalePrice"].quantile(0.99)
    df["SalePrice"] = df["SalePrice"].clip(upper=upper_price) # Cap SalePrice at 99th percentile
    return df
cap_outliers(df)

"""### **Task7** - Writing a clean_data() function  """

def clean_data(df):
  df = fix_data_types(df)
  df = handle_missing_values(df)
  df = remove_duplicates(df)
  df = cap_outliers(df)
  return df

df = clean_data(df) # apply full cleaning
df.head() #shows first 5 rows of dataset after cleaning

"""### Task8 - Adding 3 checks"""

def add_assertions(df):
    assert df.isnull().sum() == 0, "there are still missing values"
    assert df.duplicated().sum() == 0, "there are duplicate rows"
    assert (df["SalePrice"] > 0).all(), "SalePrice contains non-positive values"
    print("All assertions passed!")