# -*- coding: utf-8 -*-
"""eda_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mtdzv6VZScgnN8jS0xWnVTFvUOhGHX3_

### **Required libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from cleaning_01 import clean_data # import cleaning function from Phase 1

"""### **Task1** - Load and prepare data"""

df = pd.read_csv("AmesHousing.csv")
df = clean_data(df) # apply full cleaning

df.head() # dataset after cleaning

"""### **Task2** - Histogram + KDE"""

def plot_hist_kde(df, column, title):

    plt.figure(figsize=(8,5))
    sns.histplot(df[column], kde=True, bins=30)

    plt.title(title)
    plt.xlabel(column)
    plt.ylabel("Count")

    plt.show()

"""### 1st Feature - Living Area"""

plot_hist_kde(df, "Gr Liv Area", "Distribution of Living Area")

"""**Insight:**

The distribution of living area is slightly right skewed, indicating that most houses have moderate living space while only a small number of properties are significantly larger. This pattern suggests that the housing market is dominated by medium sized homes, with large houses representing a smaller, more premium segment. From an analytical perspective, this could mean that increases in living area may have a strong impact on price only after a certain threshold, rather than uniformly across all properties.

### 2nd Feature - Basement Area
"""

plot_hist_kde(df, "Total Bsmt SF", "Distribution of Basement Area")

"""**Insight:**

The basement area distribution is clearly right-skewed, with many houses having small or no basement space and fewer houses having large basements. This suggests that basement size is not a standard feature across all homes but rather an added value in certain properties. From a data perspective, this variability indicates that basement size may contribute differently to price depending on whether a house has a basement at all, rather than just its size.

### 3rd Feature - SalePrice
"""

plot_hist_kde(df, "SalePrice", "Distribution of SalePrice")

"""**Insight:**

The distribution of sale prices is strongly right-skewed, showing that most houses are sold within a moderate price range while only a small proportion of properties reach very high values. This indicates the presence of high-value outliers, likely representing luxury homes. From an analytical standpoint, this skewness suggests that applying transformations *such as log transformation* is useful to stabilize variance and improve model performance.

### **Task3** - Grouped Boxplots
"""

def plot_box(df, x_col, y_col, title):

    plt.figure(figsize=(10,5))
    sns.boxplot(x=df[x_col], y=df[y_col])

    plt.title(title)
    plt.xticks(rotation=45)

    plt.show()

"""### SalePrice vs Overall Quality"""

plot_box(df, "Overall Qual", "SalePrice", "SalePrice vs Overall Quality")

"""**Insight:**

There is a strong positive relationship between overall quality and sale price, whereas higher quality levels consistently correspond to higher median prices. This suggests that construction quality is one of the most influential factors in determining house value. From a modeling perspective, this feature is likely to have high predictive power and should be carefully preserved and possibly emphasized in the model.

### SalePrice vs Neighborhood
"""

plot_box(df, "Neighborhood", "SalePrice", "SalePrice vs Neighborhood")

"""**Insight:**

Sale prices vary significantly across neighborhoods, with some areas showing consistently higher median prices than others. This indicates that location plays a critical role in property valuation, likely due to differences in demand, amenities, and overall desirability. From an analytical viewpoint, neighborhood can capture complex external factors that are not directly measurable, making it a highly informative feature.

### **Task4** - Correlation Heatmap
"""

def plot_heatmap(df, target):

    corr = df.corr(numeric_only=True)

    top_features = corr[target].abs().sort_values(ascending=False).drop(target).head(10).index
    plt.figure(figsize=(8,6))
    sns.heatmap(corr.loc[top_features, top_features], annot=True, cmap="coolwarm")
    plt.title(f"Top Features Correlated with {target}")

    plt.show()

plot_heatmap(df, "SalePrice")

"""**Insight:**

The heatmap reveals the relationships among the top features most correlated with SalePrice. Some features exhibit strong correlations with each other, which may indicate redundancy and potential multicollinearity. This suggests that not all features contribute unique information, and careful feature selection may be necessary to improve model efficiency and avoid overfitting.

### **Task5** - Scatter Plot
"""

def plot_scatter(df, x_col, y_col, hue_col, title):

    plt.figure(figsize=(8,5))
    sns.scatterplot(x=df[x_col], y=df[y_col], hue=df[hue_col])
    plt.title(title)

    plt.show()

plot_scatter(df, "Gr Liv Area", "SalePrice", "Overall Qual", "Living Area vs SalePrice")

"""**Insight:**

The scatter plot shows a clear positive relationship between living area and sale price, whereas larger houses tend to have higher prices. Additionally, higher quality homes are clustered in the upper range of prices, reinforcing the combined effect of size and quality. This suggests that the interaction between these features may be important, rather than considering each feature independently.

### **Task6** - Groupby Summary
"""

def groupby_summary(df, group_col, target_col):

    result = df.groupby(group_col)[target_col].mean()

    return result

price_by_quality = groupby_summary(df, "Overall Qual", "SalePrice")
price_by_quality

price_by_quality.idxmax(), price_by_quality.idxmin()

"""**Insight:**

The average sale price increases steadily with higher overall quality levels, confirming a strong and consistent relationship between quality and price. This trend indicates that quality is not only influential but also reliable across different segments of the dataset. From an analytical perspective, this consistency makes it a robust feature for prediction and decision-making.

### **Task7** - EDA Pipeline Function
"""

def eda_pipeline(df):

    # Histograms
    plot_hist_kde(df, "Gr Liv Area", "Distribution of Living Area")
    plot_hist_kde(df, "Total Bsmt SF", "Distribution of Basement Area")
    plot_hist_kde(df, "SalePrice", "Distribution of SalePrice")

    # Boxplots
    plot_box(df, "Overall Qual", "SalePrice", "SalePrice vs Overall Quality")
    plot_box(df, "Neighborhood", "SalePrice", "SalePrice vs Neighborhood")

    # Heatmap
    plot_heatmap(df, "SalePrice")

    # Scatter
    plot_scatter(df, "Gr Liv Area", "SalePrice", "Overall Qual",
                 "Living Area vs SalePrice")

    # Groupby
    result = groupby_summary(df, "Overall Qual", "SalePrice")
    print(result)

    print("\nHighest & Lowest:")
    print(result.idxmax(), result.idxmin())

eda_pipeline(df)