# -*- coding: utf-8 -*-
"""features_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AdFG6h0DzGDkBNvHkYgOqEcUo8a4fthE

### **Required libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from cleaning_01 import clean_data  # import cleaning function from Phase 1

"""### **Task1** - Load and clean data"""

def load_and_clean_data(path):
    df = pd.read_csv(path)
    df = clean_data(df)  # apply cleaning
    return df

df = load_and_clean_data("AmesHousing.csv") #load raw data
df.head()

"""### **Task2** - Split the Data"""

# split features and target into train and test sets
def split_data(df):
    X = df.drop("SalePrice", axis=1)
    y = df["SalePrice"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = split_data(df)
X_train.shape, X_test.shape # check train and test sizes

"""### **Task3** - One-Hot Encoding"""

def one_hot_encode(X_train, X_test):
    categorical_cols = ["Neighborhood", "SaleCondition"] # one-hot encode nominal categorical features

    categorical_cols = [col for col in categorical_cols if col in X_train.columns]

    X_train = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)
    X_test = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True) # keep only columns that exist in the dataset

    X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0) # align train and test columns
    return X_train, X_test

X_train, X_test = one_hot_encode(X_train, X_test)
X_train.head() # preview encoded features

"""### **Task4** - Ordinal Encoding"""

def encode_ordinal(X_train, X_test):
    quality_map = {"Po":1, "Fa":2, "TA":3, "Gd":4, "Ex":5}

    X_train["Exter Qual"] = X_train["Exter Qual"].map(quality_map)
    X_test["Exter Qual"] = X_test["Exter Qual"].map(quality_map) # encode ordinal feature

    return X_train, X_test

X_train, X_test = encode_ordinal(X_train, X_test)
X_train["Exter Qual"].head() # check encoded ordinal feature

"""### **Task5** - Create Domain Features"""

def create_domain_features(X_train, X_test):
    for df_ in [X_train, X_test]:
        df_["total_bathrooms"] = (
            df_["Full Bath"] + 0.5 * df_["Half Bath"] +
            df_["Bsmt Full Bath"] + 0.5 * df_["Bsmt Half Bath"]
        ) # total bathrooms including halves

        df_["house_age"] = df_["Yr Sold"] - df_["Year Built"] # age of house
    return X_train, X_test

X_train, X_test = create_domain_features(X_train, X_test)
X_train[["total_bathrooms","house_age"]].head() # check new domain features

"""### **Task6** - Interaction Feature"""

def create_interaction_feature(X_train, X_test):
    for df_ in [X_train, X_test]:
        df_["quality_living_area"] = df_["Overall Qual"] * df_["Gr Liv Area"] # capture combined effect of quality and living area
    return X_train, X_test

X_train, X_test = create_interaction_feature(X_train, X_test)
X_train["quality_living_area"].head() # preview interaction feature

"""### **Task7** - Log Transform Target"""

def log_transform_target(y_train, y_test):
    plt.figure(figsize=(8,5))
    sns.histplot(y_train, kde=True)
    plt.title("SalePrice Before Log")
    plt.show() # before log

    y_train = np.log1p(y_train)
    y_test = np.log1p(y_test) # applying log1p

    plt.figure(figsize=(8,5))
    sns.histplot(y_train, kde=True)
    plt.title("SalePrice After Log")
    plt.show() # after log

    return y_train, y_test

y_train, y_test = log_transform_target(y_train, y_test)

"""### **Task8** - Binning Feature"""

def create_age_bins(X_train, X_test):
    for df_ in [X_train, X_test]:
        df_["age_group"] = pd.cut(
            df_["house_age"],
            bins=[0,10,30,150],
            labels=["New","Recent","Old"]
        )
    return X_train, X_test


X_train, X_test = create_age_bins(X_train, X_test)
X_train["age_group"].head() # preview binned feature

"""### **Task9** - Scale Features"""

def scale_features(X_train, X_test):
    numeric_cols = [
        "Gr Liv Area", "Total Bsmt SF", "total_bathrooms",
        "house_age", "quality_living_area", "Exter Qual"
    ]

    scaler = StandardScaler()
    X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
    X_test[numeric_cols] = scaler.transform(X_test[numeric_cols]) # scale numeric features using StandardScaler

    return X_train, X_test

X_train, X_test = scale_features(X_train, X_test)
X_train.head() # preview scaled features

"""### **Task10** - Remove Highly Correlated Features"""

def remove_high_correlation(X_train, X_test, threshold=0.95):

    numeric_X_train = X_train.select_dtypes(include=[np.number]) # select only numeric columns

    corr_matrix = numeric_X_train.corr().abs() # compute correlation matrix

    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

    to_drop = [col for col in upper.columns if any(upper[col] > threshold)] # find highly correlated features
    X_train = X_train.drop(columns=to_drop)
    X_test = X_test.drop(columns=to_drop, errors="ignore")

    return X_train, X_test, to_drop

X_train, X_test, dropped_features = remove_high_correlation(X_train, X_test)
print(dropped_features) # show removed correlated features

"""### **Task11** - Feature Engineering Pipeline"""

def feature_engineering_pipeline(df):

    X_train, X_test, y_train, y_test = split_data(df)
    X_train, X_test = one_hot_encode(X_train, X_test)
    X_train, X_test = encode_ordinal(X_train, X_test)
    X_train, X_test = create_domain_features(X_train, X_test)
    X_train, X_test = create_interaction_feature(X_train, X_test)
    y_train, y_test = log_transform_target(y_train, y_test)
    X_train, X_test = create_age_bins(X_train, X_test)
    X_train, X_test = scale_features(X_train, X_test)
    X_train, X_test, dropped_features = remove_high_correlation(X_train, X_test)

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = feature_engineering_pipeline(df)
X_train.head() # preview engineered features