# -*- coding: utf-8 -*-
"""math_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icNGua22kft9tIuMnO_m3zD5xyroSMTP

### **Required Libraries**
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

from cleaning_01 import clean_data # import cleaning function from Phase 1

"""### **Task1** - Load and Clean Data"""

df = pd.read_csv("AmesHousing.csv")
df = clean_data(df)

df.head()

"""### **Task2** - Compute Mean & Standard Deviation"""

def compute_mean_std(arr):

    mean = np.sum(arr) / len(arr)  # calculate mean manually
    std = np.sqrt(np.sum((arr - mean)**2) / len(arr))  # calculate std manually

    return mean, std

mean, std = compute_mean_std(df["SalePrice"].values)  # apply function on target column
mean, std  # display results

"""### **Task3** - Standardization

### Manual vs Sklearn
"""

def manual_standardize(arr):

    mean = np.mean(arr)  # calculate mean
    std = np.std(arr)    # calculate std
    z = (arr - mean) / std  # apply standardization formula

    return z

manual_z = manual_standardize(df["Gr Liv Area"].values)  # manual scaling
scaler = StandardScaler()  # sklearn scaler
sklearn_z = scaler.fit_transform(df[["Gr Liv Area"]]).flatten()  # sklearn scaling
manual_z[:5], sklearn_z[:5]  # compare first 5 values

"""### **Task4** - Cosine Similarity"""

def cosine_similarity(a, b):

    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))  # cosine formula

numeric_cols = df.select_dtypes(include=np.number).columns  # select numeric columns

high_vec = df.loc[df["SalePrice"].idxmax(), numeric_cols]  # highest price row
low_vec = df.loc[df["SalePrice"].idxmin(), numeric_cols]   # lowest price row
cosine_similarity(high_vec, low_vec)  # compute similarity

"""### **Task5** - Probability Estimation"""

def estimate_probability(df):

    high_quality = df[df["Overall Qual"] >= 7]  # filter high quality houses
    threshold = df["SalePrice"].median()  # define threshold (median)
    probability = (high_quality["SalePrice"] > threshold).mean()  # compute probability

    return probability

estimate_probability(df)  # calculate probability

def math_pipeline(df):

    mean, std = compute_mean_std(df["SalePrice"].values)
    print(f"Mean: {mean:.2f} | Std: {std:.2f}")

    manual_z = manual_standardize(df["Gr Liv Area"].values)
    scaler = StandardScaler()
    sklearn_z = scaler.fit_transform(df[["Gr Liv Area"]]).flatten()
    print(f"\nStandardization (first 5):\nManual: {manual_z[:5]}\nSklearn: {sklearn_z[:5]}")

    numeric_cols = df.select_dtypes(include=np.number).columns
    high_vec = df.loc[df["SalePrice"].idxmax(), numeric_cols]
    low_vec = df.loc[df["SalePrice"].idxmin(), numeric_cols]
    sim = cosine_similarity(high_vec, low_vec)
    print(f"\nCosine Similarity: {sim:.4f}")

    prob = estimate_probability(df)
    print(f"\nProbability: {prob:.2f}")

    return mean, std, sim, prob
results = math_pipeline(df)